/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "kid-data": {
        "NOT_ENOUGH_COIN": string;
        "INVALID_LESSON_UNLOCK": string;
        "NOT_ENOUGH_ENERGY": string;
    };
    "kid-lesson": {
        "INVALID_DIFFICULTY": string;
    };
    "message": {
        "INVALID": string;
        "IS_EXISTED": string;
        "NOT_PERMISSION": string;
        "NOT_FOUND": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
